-- Debug model to test for nulls in any column of the specified model

-- Make sure this debug model does NOT create a view/table in Snowflake
{{ config(materialized='ephemeral') }} --- Initially we have not set this, hence it created view in snowflake

{% set model_to_test = ref('fct_genome_score') %}

{{ no_nulls_in_cols(model_to_test) }}

-- This is a SINGULAR test in dbt.
-- Purpose:
-- We want to validate that the "relevance" score from the fct_genome_score model
-- is never negative. In the Business context, a genome relevance score should
-- always be between 0 and 1. Any negative value indicates bad, corrupted, or
-- wrongly processed data.

{# ==============================================================================
    MODEL NAME: tmp_debug_null_test

    PURPOSE:
    --------
    This file exists ONLY to help you debug or inspect the SQL generated by
    the macro `no_nulls_in_cols`.

    IMPORTANT:
    ----------
    - dbt will normally create a physical object (a VIEW) in Snowflake
      because the default materialization for models is `view`.

    - However, since we DO NOT want this debug model to create anything
      in Snowflake, we configure it to be `ephemeral`.

    WHAT DOES EPHEMERAL MEAN?
    --------------------------
    - dbt compiles the SQL (so you can inspect it)
    - but dbt does NOT create a view or table in Snowflake
    - ephemeral models are injected as CTEs inside downstream models

    HOW TO VIEW THE GENERATED SQL:
    -------------------------------
    1. Run:       dbt compile
    2. Navigate:  target/compiled/<project_name>/models/tmp_debug_null_test.sql
    3. Open the file → you will see the full SQL generated by the macro.

============================================================================== #}

