version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        # Adding a warning for not_null instead of failing the run
        data_tests:
          - unique
          - not_null:
              severity: warn

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        # Default behavior: not_null test will fail the run if nulls are present
        data_tests:
          - unique
          - not_null